// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/mime;

# Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
public isolated client class Client {
    final http:Client clientEp;

    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.mistral.ai/v1") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, timeout: config.timeout, forwarded: config.forwarded, poolConfig: config.poolConfig, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, validation: config.validation};
        do {
            if config.http1Settings is ClientHttp1Settings {
                ClientHttp1Settings settings = check config.http1Settings.ensureType(ClientHttp1Settings);
                httpClientConfig.http1Settings = {...settings};
            }
            if config.http2Settings is http:ClientHttp2Settings {
                httpClientConfig.http2Settings = check config.http2Settings.ensureType(http:ClientHttp2Settings);
            }
            if config.cache is http:CacheConfig {
                httpClientConfig.cache = check config.cache.ensureType(http:CacheConfig);
            }
            if config.responseLimits is http:ResponseLimitConfigs {
                httpClientConfig.responseLimits = check config.responseLimits.ensureType(http:ResponseLimitConfigs);
            }
            if config.secureSocket is http:ClientSecureSocket {
                httpClientConfig.secureSocket = check config.secureSocket.ensureType(http:ClientSecureSocket);
            }
            if config.proxy is http:ProxyConfig {
                httpClientConfig.proxy = check config.proxy.ensureType(http:ProxyConfig);
            }
        }
        http:Client httpEp = check new (serviceUrl, httpClientConfig);
        self.clientEp = httpEp;
        return;
    }

    # Delete File
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function delete files/[string fileId](map<string|string[]> headers = {}) returns DeleteFileOut|error {
        string resourcePath = string `/files/${getEncodedUri(fileId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Unarchive Fine Tuned Model
    #
    # + modelId - The ID of the model to unarchive.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function delete fine_tuning/models/[string modelId]/archive(map<string|string[]> headers = {}) returns UnarchiveFTModelOut|error {
        string resourcePath = string `/fine_tuning/models/${getEncodedUri(modelId)}/archive`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Delete Model
    #
    # + modelId - The ID of the model to delete.
    # + headers - Headers to be sent with the request 
    # + return - Successful Response 
    resource isolated function delete models/[string modelId](map<string|string[]> headers = {}) returns DeleteModelOut|error {
        string resourcePath = string `/models/${getEncodedUri(modelId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get Batch Jobs
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    resource isolated function get batch/jobs(map<string|string[]> headers = {}, *JobsApiRoutesBatchGetBatchJobsQueries queries) returns BatchJobsOut|error {
        string resourcePath = string `/batch/jobs`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get Batch Job
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function get batch/jobs/[string jobId](map<string|string[]> headers = {}) returns BatchJobOut|error {
        string resourcePath = string `/batch/jobs/${getEncodedUri(jobId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # List Files
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    resource isolated function get files(map<string|string[]> headers = {}, *FilesApiRoutesListFilesQueries queries) returns ListFilesOut|error {
        string resourcePath = string `/files`;
        map<Encoding> queryParamEncoding = {"sample_type": {style: FORM, explode: true}, "source": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Retrieve File
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function get files/[string fileId](map<string|string[]> headers = {}) returns RetrieveFileOut|error {
        string resourcePath = string `/files/${getEncodedUri(fileId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Download File
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function get files/[string fileId]/content(map<string|string[]> headers = {}) returns byte[]|error {
        string resourcePath = string `/files/${getEncodedUri(fileId)}/content`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get Signed Url
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    resource isolated function get files/[string fileId]/url(map<string|string[]> headers = {}, *FilesApiRoutesGetSignedUrlQueries queries) returns FileSignedURL|error {
        string resourcePath = string `/files/${getEncodedUri(fileId)}/url`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get Fine Tuning Jobs
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    resource isolated function get fine_tuning/jobs(map<string|string[]> headers = {}, *JobsApiRoutesFineTuningGetFineTuningJobsQueries queries) returns JobsOut|error {
        string resourcePath = string `/fine_tuning/jobs`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get Fine Tuning Job
    #
    # + jobId - The ID of the job to analyse.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function get fine_tuning/jobs/[string jobId](map<string|string[]> headers = {}) returns DetailedJobOut|error {
        string resourcePath = string `/fine_tuning/jobs/${getEncodedUri(jobId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # List Models
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful Response 
    resource isolated function get models(map<string|string[]> headers = {}) returns ModelList|error {
        string resourcePath = string `/models`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Retrieve Model
    #
    # + modelId - The ID of the model to retrieve.
    # + headers - Headers to be sent with the request 
    # + return - Successful Response 
    resource isolated function get models/[string modelId](map<string|string[]> headers = {}) returns Response\ Retrieve\ Model\ V1\ Models\ \ Model\ Id\ \ Get|error {
        string resourcePath = string `/models/${getEncodedUri(modelId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Update Fine Tuned Model
    #
    # + modelId - The ID of the model to update.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function patch fine_tuning/models/[string modelId](UpdateFTModelIn payload, map<string|string[]> headers = {}) returns FTModelOut|error {
        string resourcePath = string `/fine_tuning/models/${getEncodedUri(modelId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Agents Completion
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful Response 
    resource isolated function post agents/completions(AgentsCompletionRequest payload, map<string|string[]> headers = {}) returns ChatCompletionResponse|error {
        string resourcePath = string `/agents/completions`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Create Batch Job
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function post batch/jobs(BatchJobIn payload, map<string|string[]> headers = {}) returns BatchJobOut|error {
        string resourcePath = string `/batch/jobs`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Cancel Batch Job
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function post batch/jobs/[string jobId]/cancel(map<string|string[]> headers = {}) returns BatchJobOut|error {
        string resourcePath = string `/batch/jobs/${getEncodedUri(jobId)}/cancel`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Chat Completion
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful Response 
    resource isolated function post chat/completions(ChatCompletionRequest payload, map<string|string[]> headers = {}) returns ChatCompletionResponse|error {
        string resourcePath = string `/chat/completions`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Moderations Chat
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful Response 
    resource isolated function post chat/moderations(ChatModerationRequest payload, map<string|string[]> headers = {}) returns ClassificationResponse|error {
        string resourcePath = string `/chat/moderations`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Embeddings
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful Response 
    resource isolated function post embeddings(EmbeddingRequest payload, map<string|string[]> headers = {}) returns EmbeddingResponse|error {
        string resourcePath = string `/embeddings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Upload File
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function post files(MultiPartBodyParams payload, map<string|string[]> headers = {}) returns UploadFileOut|error {
        string resourcePath = string `/files`;
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(payload);
        request.setBodyParts(bodyParts);
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Fim Completion
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful Response 
    resource isolated function post fim/completions(FIMCompletionRequest payload, map<string|string[]> headers = {}) returns FIMCompletionResponse|error {
        string resourcePath = string `/fim/completions`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Create Fine Tuning Job
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    resource isolated function post fine_tuning/jobs(JobIn payload, map<string|string[]> headers = {}, *JobsApiRoutesFineTuningCreateFineTuningJobQueries queries) returns Response|error {
        string resourcePath = string `/fine_tuning/jobs`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    resource isolated function post fine_tuning/jobs/[string jobId]/'start(map<string|string[]> headers = {}) returns DetailedJobOut|error {
        string resourcePath = string `/fine_tuning/jobs/${getEncodedUri(jobId)}/start`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Cancel Fine Tuning Job
    #
    # + jobId - The ID of the job to cancel.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function post fine_tuning/jobs/[string jobId]/cancel(map<string|string[]> headers = {}) returns DetailedJobOut|error {
        string resourcePath = string `/fine_tuning/jobs/${getEncodedUri(jobId)}/cancel`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Archive Fine Tuned Model
    #
    # + modelId - The ID of the model to archive.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    resource isolated function post fine_tuning/models/[string modelId]/archive(map<string|string[]> headers = {}) returns ArchiveFTModelOut|error {
        string resourcePath = string `/fine_tuning/models/${getEncodedUri(modelId)}/archive`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Moderations
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful Response 
    resource isolated function post moderations(ClassificationRequest payload, map<string|string[]> headers = {}) returns ClassificationResponse|error {
        string resourcePath = string `/moderations`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # OCR
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful Response 
    resource isolated function post ocr(OCRRequest payload, map<string|string[]> headers = {}) returns OCRResponse|error {
        string resourcePath = string `/ocr`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }
}
