# Any error occurred during parsing OpenAPI specification is classified under this error type.
public type OpenApiParsingError distinct error;

# Stackoverflow errors due to lenthy OpenAPI specification or cyclic references in the specification.
public type ParsingStackOverflowError distinct OpenApiParsingError;

# Errors due to unsupported OpenAPI specification version.
public type UnsupportedOpenApiVersion distinct OpenApiParsingError;

# Errors due to invalid or broken references in the OpenAPI specification.
public type InvalidReferenceError distinct OpenApiParsingError;

# Errors due to incomplete OpenAPI specification.
public type IncompleteSpecificationError distinct OpenApiParsingError;

# Errors due to unsupported media type.
public type UnsupportedMediaTypeError distinct OpenApiParsingError;

# Any error occurred during parsing HTTP response is classified under this error type.
public type HttpResponseParsingError distinct error;

# Any error occurred during LLM generation is classified under this error type.
public type LlmError distinct error;

# Errors due to invalid action generated by the LLM.
type LlmActionParseError distinct LlmError;

# Errors occurred during LLM generation.
public type LlmGenerationError distinct LlmError;

# Errors occurred due to termination of the Agent's execution.
public type TaskTerminationError distinct error;

